<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>
	<PropertyGroup>
		<!-- Set this value to your mod's Steam Workhop ID -->
		<SteamId>3785407853</SteamId>
		<!-- Quasimorph game Steam AppID, used to locate the game install in the registry -->
		<GAME_STEAM_ID>2059170</GAME_STEAM_ID>
	</PropertyGroup>
	<PropertyGroup>
		<GAME_NAME>Quasimorph</GAME_NAME>
		<GAME_PATH Condition="!Exists('$(GAME_PATH)')">$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App $(GAME_STEAM_ID)', 'InstallLocation', null, RegistryView.Registry64, RegistryView.Registry32))</GAME_PATH>
		<_SteamLibraryPath>$([MSBuild]::GetRegistryValueFromView('HKEY_CURRENT_USER\SOFTWARE\Valve\Steam', 'SteamPath', null, RegistryView.Registry32))</_SteamLibraryPath>
		<GAME_PATH Condition="!Exists('$(GAME_PATH)') AND '$(_SteamLibraryPath)' != ''">$(_SteamLibraryPath)\steamapps\common\$(GAME_NAME)</GAME_PATH>
		<GAME_PATH Condition="!Exists('$(GAME_PATH)')">C:\Program Files\Steam\steamapps\common\$(GAME_NAME)</GAME_PATH>
		<GAME_PATH Condition="!Exists('$(GAME_PATH)')">C:\Program Files (x86)\Steam\steamapps\common\$(GAME_NAME)</GAME_PATH>
		<WorkshopPath>$(GAME_PATH)\..\..\workshop\content\2059170\$(SteamId)\</WorkshopPath>
		<ManagedPath>$(GAME_PATH)\$(GAME_NAME)_Data\Managed\</ManagedPath>
		<McmPath>$(GAME_PATH)\..\..\workshop\content\2059170\3469678797\MCM.dll</McmPath>
		<AssemblyVersion>$(VersionPrefix)</AssemblyVersion>
		<PackageFolder>$(ProjectDir)../package/</PackageFolder>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Assembly-CSharp">
		  <HintPath>$(ManagedPath)Assembly-CSharp.dll</HintPath>
		  <Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine">
		  <HintPath>$(ManagedPath)UnityEngine.dll</HintPath>
		  <Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
		  <HintPath>$(ManagedPath)UnityEngine.CoreModule.dll</HintPath>
		  <Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.InputLegacyModule">
		  <HintPath>$(ManagedPath)UnityEngine.InputLegacyModule.dll</HintPath>
		  <Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
		  <HintPath>$(ManagedPath)UnityEngine.UI.dll</HintPath>
		  <Private>false</Private>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
		  <HintPath>$(ManagedPath)Unity.TextMeshPro.dll</HintPath>
		  <Private>false</Private>
		</Reference>
		<Reference Include="MCM">
		  <HintPath>$(McmPath)</HintPath>
		  <Private>false</Private>
		</Reference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.2" ExcludeAssets="runtime" />
		<PackageReference Include="Lib.harmony" Version="2.3.3" ExcludeAssets="runtime" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" ExcludeAssets="runtime" />
		<PackageReference Include="Newtonsoft.json" Version="13.0.3" ExcludeAssets="runtime" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" ExcludeAssets="runtime" />
	</ItemGroup>

	<!--Clean out the Steam Workshop folder to prevent artifacts such as references no longer used-->
	<Target BeforeTargets="PostBuildEvent" Condition="'$(SteamId)'!=''" Name="WorkshopFolderClean">
		<ItemGroup>
			<FilesToDelete Include="$(WorkshopPath)*" />
		</ItemGroup>
		<Delete Files="@(FilesToDelete)" />
	</Target>

	<Target Name="ModBaseItems" AfterTargets="PostBuildEvent">
		<Copy SourceFiles="../modmanifest.json" DestinationFolder="$(TargetDir)" />
		<Copy SourceFiles="../localization.json" DestinationFolder="$(TargetDir)" />
		<Copy SourceFiles="../media/thumbnail.png" DestinationFolder="$(TargetDir)" ContinueOnError="true" />
	</Target>

	<Target Name="NoSteamIdMessage" Condition="'$(SteamId)'==''" AfterTargets="PostBuildEvent">
		<Message Importance="high" Text="The SteamId is not set in the project.  Aborting Steam Workshop folder deployment." />
	</Target>
		
	<Target Name="SteamWorkshopDeploy" Condition="'$(SteamId)'!=''" AfterTargets="PostBuildEvent">
		<ItemGroup>
			<BuildSource Include="$(TargetDir)/*.*" />
		</ItemGroup>
		<MakeDir Directories="$(WorkshopPath)" ContinueOnError="true" />
		<Copy SourceFiles="@(BuildSource)" DestinationFolder="$(WorkshopPath)" />
	</Target>

	<Target Name="ReleasePbdDelete" Condition="'$(SteamId)'!='' and '$(Configuration)'=='Release'" AfterTargets="PostBuildEvent">
		<Delete Files="$(WorkshopPath)/$(TargetName).pdb" />
	</Target>


	<!-- Create the .Zip file release-->
	<Target Condition="'$(SteamId)'!=''" AfterTargets="PostBuildEvent" Name="PostBuildPackage">
		<ItemGroup>
			<WorkshopSourceFile Include="$(WorkshopPath)*.*" />
		</ItemGroup>

		<RemoveDir Directories="$(PackageFolder)" />
		<MakeDir Directories="$(PackageFolder)" />
		<Copy SourceFiles="@(WorkshopSourceFile)" DestinationFolder="$(PackageFolder)$(TargetName)"></Copy>
		<Delete Files="$(PackageFolder)$(TargetName)/$(TargetName).pdb" />
		<ZipDirectory SourceDirectory="$(PackageFolder)" DestinationFile="$(PackageFolder)../$(TargetName).zip" Overwrite="true" />
	</Target>
	<ItemGroup>
		<Reference Update="System">
			<Private>False</Private>
		</Reference>
	</ItemGroup>
</Project>